# Generated by Django 5.0.8 on 2024-09-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('session', models.CharField(choices=[('w', 'Winter'), ('s', 'Summer')], max_length=1)),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (1, 'Term 2')])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('full_course_name', models.CharField(max_length=100)),
                ('terms_offered', models.ManyToManyField(help_text='select the terms in which the course is offered', to='courselist.term')),
            ],
            options={
                'unique_together': {('subject', 'number')},
            },
        ),
    ]
