# Generated by Django 5.0.8 on 2024-09-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courselist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='terms_offered',
            field=models.ManyToManyField(help_text='Select the terms in which the course is offered.', to='courselist.term'),
        ),
    ]
