# Generated by Django 5.0.8 on 2024-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courselist', '0002_course_credits_alter_course_full_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_science_credit',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
