# Generated by Django 5.0.8 on 2024-09-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courselist', '0004_remove_course_credits_remove_course_full_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
    ]
